### ISSUE TITLE
Small fix needed for OCaml 4.10 compat.

### ISSUE THREAD

**Issue by rwmjones** [garrigue/lablgtk#103]
Which branch of git corresponds to lablgtk2?  Anyway for OCaml 4.10 you will need a very small fix:

https://src.fedoraproject.org/rpms/ocaml-lablgtk/blob/master/f/lablgtk-2.18.8-ocaml410.patch

**Comment by XVilka** [comment]
This one https://github.com/garrigue/lablgtk/tree/master

**Comment by ejgallego** [comment]
Maybe renaming the branch would help? Current situation with master may be a bit confusing indeed.

**Comment by garrigue** [comment]
lablgtk-2.18.9 is already released and available on opam, with a similar fix.
However, it seems that ocaml 4.10 is going to change its headers again, and will require a different fix, so please wait for 2.18.10 before packaging it.

**Comment by rwmjones** [comment]
Ah I was looking at the website not the "Releases" list in github.  Anyway since there's already an equivalent fix let's close this bug.

**Comment by rwmjones** [comment]
Oh and the branch naming and especially the obsolete branches - very confusing!
