### ISSUE TITLE
Linking issues with gcc-10

### ISSUE THREAD

**Issue by vprevosto** [garrigue/lablgtk#112]
I'm unable to compile labgtk3 3.1.0 since I've upgraded my gcc version, with ld reporting multiple definitions of `ml_table_extension_events`, declared in `src/ml_gdk.h` on line 89. The symptom looks similar as an [issue](https://github.com/ocaml/ocaml/issues/9144) reported against OCaml itself, and replacing `CAMLexport` by `CAMLextern` in the declaration (which technically, without the `extern`, is a "tentative definition"), as suggested there, indeed fixes the issue.

**Comment by garrigue** [comment]
Already fixed by #105 
Does it mean we need another release?

**Comment by vprevosto** [comment]
Oops, sorry I didn't see an open issue on the subject, and I didn't check the closed ones 😁. I think that a new release would be good indeed. I initially stumbled upon that by trying to compile the official lablgtk3 package on a new opam switch, and I imagine that this will happen to others, too, especially when 4.11.0 will be out.

**Comment by garrigue** [comment]
Fixed in 3.1.1.
