### ISSUE TITLE
version information into dune-project (lablgtk3)

### ISSUE THREAD

**Issue by yozot** [garrigue/lablgtk#123]
On OpenBSD/amd64, I found that the output of ```ocamlfind list``` does not show version information.
```
$ ocamlfind list
........
lablgtk2            (version: 2.18.8)
lablgtk2.auto-init  (version: n/a)
lablgtk2.glade      (version: n/a)
lablgtk2.gnomecanvas (version: n/a)
lablgtk2.rsvg       (version: n/a)
lablgtk2.sourceview2 (version: n/a)
lablgtk3            (version: n/a)
lablgtk3-sourceview3 (version: n/a)
```

configure.ml  of coq-8.13 uses this method to detect the version of lablgtk3.

Adding ```(version "3.1.1")``` to dune-project and rebuilding lablgtk3, the version information is registered to ```lib/ocaml/lablgtk3/META```, and I can build coq 8.13.1 with coqide now.

```
$ ocamlfind list
........
lablgtk2            (version: 2.18.8)
lablgtk2.auto-init  (version: n/a)
lablgtk2.glade      (version: n/a)
lablgtk2.gnomecanvas (version: n/a)
lablgtk2.rsvg       (version: n/a)
lablgtk2.sourceview2 (version: n/a)
lablgtk3            (version: 3.1.1)
lablgtk3-sourceview3 (version: 3.1.1)
```

**Comment by ejgallego** [comment]
You are building the package incorrectly, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971439

**Comment by yozot** [comment]
Wow! Thanks.
I can find other instances in [OpenBSD ports tree](https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/) which should be fixed...

**Comment by ejgallego** [comment]
> I can find other instances in [OpenBSD ports tree](https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/) which should be fixed...

Yup, unfortunately this seems like a pervasive problem, I have submitted an issue to dune upstream as to try to improve the documentation.
