### ISSUE TITLE
please clarify licence of examples/*

### ISSUE THREAD

**Issue by treinen** [garrigue/lablgtk#15]
Hi,

most of the files under examples/ have a header "There is no specific licensing policy, but you may freely take inspiration from the code, and copy parts of it in your application." It is not clear what that means.
For instance, is one allowed to redistribute the code, or derived works of this code ? If yes, under
which licence?

If you wish that there are no copyright restrictions on the code then please state this clearly, or otherwise choose one of the existing permissive licences thar are around.

-Ralf

**Comment by garrigue** [comment]
Thank you for the report.
Since these are just small examples, I put everything in the public domain, updating the wording in each file:
```
(**************************************************************************)
(*    Lablgtk - Examples                                                  *)
(*                                                                        *)
(*    This code is in the public domain.                                  *)
(*    You may freely copy parts of it in your application.                *)
(*                                                                        *)
(**************************************************************************)
```

Does it look OK now?

**Comment by treinen** [comment]
Am I only allowed to copy parts of an example file, and not the complete file?
 
I suggest to simply drop the second phrase, and to just keep "This code is in the public domain", if this your intention.
