### ISSUE TITLE
Outdated `src/.depend` file in 2.18.12 release tarball

### ISSUE THREAD

**Issue by trofi** [garrigue/lablgtk#155]
The `src/.depend` file included in latest release is outdated and does not
contain a dependency of 'gtkThInit.cmo' on 'gtkThread.cmi'.

As a result build on `make --shuffle` (added in
https://savannah.gnu.org/bugs/index.php?62100) fails in about 50% cases
as:

    make -C src world
    make[1]: Entering directory '/build/source/src'
    ocamlc.opt   -w s-3+52 -c  gtkThInit.ml
    File "gtkThInit.ml", line 27, characters 13-28:
    27 | let thread = GtkThread.start ()
                      ^^^^^^^^^^^^^^^
    Error: Unbound module GtkThread
    make[1]: *** [Makefile:193: gtkThInit.cmo] Error 2 shuffle=1656165991
    make[1]: Leaving directory '/build/source/src'
    make: *** [Makefile:5: world] Error 2 shuffle=1656165991

If I run `make depend` against `ocaml-4.13` I see expected depend:

```
$ ./configure
$ make depend
$ cat src/.depend
...
gtkThInit.cmo : \
    gtkThread.cmi
...
```

**Comment by garrigue** [comment]
Done in 91ce823475
