### ISSUE TITLE
README refers to lablgtk2

### ISSUE THREAD

**Issue by treinen** [garrigue/lablgtk#16]
The README file should be updated for lablgtk3

**Comment by garrigue** [comment]
Are you looking at the lablgtk3 branch?
It explicitly says lablgtk3, and the only way lablgtk2 appears is to clarify the relation to it.

**Comment by treinen** [comment]
Oups, indeed, wrong branch. Sorry about the noise. 

One minor point: the README talks about compiling the SVN version, that should probably be
Git now.
