### ISSUE TITLE
fails to compile on ocaml 4.02.3

### ISSUE THREAD

**Issue by treinen** [garrigue/lablgtk#17]
README says that one needs ocaml-3.11 or more (4.06 is preferred)

When compiling on a debian stable machine (ocaml 4.02.3):

    ocamlc.opt   -w s-3+52 -warn-error A-52 -c  gutf8.ml
    File "gutf8.ml", line 71, characters 26-27:
    Error: The function applied to this argument has type int -> int -> string
    This argument cannot be applied with label ~pos
    Makefile:192: recipe for target 'gutf8.cmo' failed

For debian it would be fine to require ocaml >= 4.05, but then please say so and adapt the check in
configure.in accordingly.

-Ralf.

**Comment by treinen** [comment]
in fact it is the same with ocaml 4.05.0. -Ralf.

**Comment by garrigue** [comment]
Thank you for the report.
Indeed 4.05 didn't have Bytes in StdLabels.
I fixed that both in master and lablgtk3, requiring 4.05 to be sure.

**Comment by treinen** [comment]
Thanks, it compiles fine now on my machine (ocaml 4.05.0).
