### ISSUE TITLE
"make install" should create missing directories

### ISSUE THREAD

**Issue by treinen** [garrigue/lablgtk#18]
"make install: should create missing directories (usr/lib etc.). This is important when using a nonempty value for DESTDIR since then one cannot assume any already existing directories. Packagers from software distributions use this to install into an empty staging directory.

For instance :

    % DESTDIR=/home/treinen make install
    make -C src install
    make[1]: Entering directory '/home/treinen/projects/lablgtk/src'
    mkdir -p "/home/treinen/usr/local/bin"
    mkdir -p "/home/treinen/usr/local/lib/ocaml/4.05.0"
    touch: cannot touch '/home/treinen/usr/lib/ocaml/ld.conf': No such file or directory
    make[1]: *** [Makefile:382: findlib-install] Error 1
    make[1]: Leaving directory '/home/treinen/projects/lablgtk/src'
    make: *** [Makefile:5: install] Error 2

Here the problem is that /home/treinen/usr/lib does not exist (not the missing "local")

**Comment by treinen** [comment]
Do you mean that src/Makefile could be replaced by one that just calls dune? That would probably be an improvement for lablgtk in general since the Makefile is quite complex.

**Comment by ejgallego** [comment]
I think so, of course OMMV, but using a more uniform build system for Debian Ocaml could help; I'll try to finish the Dune port this week [just missing a few extra packages] and we can see.

**Comment by ejgallego** [comment]
In fact you don't need to replace the makefile, you could just call `dune build` from the Dunerized Debian setup.

**Comment by treinen** [comment]
I dont want to use for debian a completely different build-system than upstream. if the current makefile can be replaced by dune then it is up to upstream to take that decision.

**Comment by ejgallego** [comment]
I think the plan is to have both systems upstream, so Debian would be free to choose.

**Comment by treinen** [comment]
There was no --libdir option in the example invocation in the initial bug report.

The Makefile does not always create all useful directories. The problem is that the touch command does not create missing path components. This patch fixes that: 
[lablgtk3-makefile-patch.txt](https://github.com/garrigue/lablgtk/files/2644058/lablgtk3-makefile-patch.txt)

**Comment by garrigue** [comment]
OK, I will apply your patch, but it's still confusing: there is only one ld.conf file, which should be in stublibs, and you're not supposed to overwrite it...
Maybe it's just that I don't understand well how findlib works.

**Comment by garrigue** [comment]
Note that your error is still strange: I don't see why your ld.conf would reside is /usr/lib/ocaml, whereas the real ocaml is in /usr/local/lib. There is supposed to be one ocaml ld.conf file by version of ocaml.

**Comment by garrigue** [comment]
patch applied to master and lablgtk3, commits cc0e08ef and 5c9341d

**Comment by treinen** [comment]
Thanks.

In fact it is your makefile that directly touches ocaml.ld.conf, and that could fail when DESTDIR is set. I was just fixing this. Besides I don't know either whether that file is useful when *installing* stuff using
findlib.

Concerning /usr/local: When ocaml is installed by the operating system (this includes in particular installation via some distribution, like debian) then it goes into /usr/{lib,bin,...} and not into /usr/local. The operating system is not supposed to install stuff in /usr/local, as stated by the File Hierarchy Standard. /usr/local is for the sysadmin to install additional stuff.
