### ISSUE TITLE
Add releases at GitHub releases page

### ISSUE THREAD

**Issue by XVilka** [garrigue/lablgtk#30]
Here: https://github.com/garrigue/lablgtk/releases

Nowadays people tend to check this page when visiting GitHub project.

**Comment by ejgallego** [comment]
Note that dune-release does that automatically.

**Comment by garrigue** [comment]
The releases are at `http://lablgtk.forge.ocamlcore.org`.
This is originally an ocamlcore project, at this point only the git repository has moved, to simplify pull requests.
I'd be happy to move the releases to GitHub too, but I first need to understand how one does it. (I do not want to put all the files in the repository in the release.)

**Comment by ejgallego** [comment]
Can this be closed @XVilka ?

**Comment by garrigue** [comment]
Releases are now on the releases page, as OCaml core is dead for edition.
