### ISSUE TITLE
src/propcc.ml and src/propcc.ml4 are out of sync in lablgtk3 branch

### ISSUE THREAD

**Issue by vprevosto** [garrigue/lablgtk#36]
Commit a0c89b29f46e516d2f64137baba797da68f7a6aa did update `src/propcc.ml` with a new `boxed` type, but left `src/propcc.ml4` untouched. This results in potential issue when using a fresh clone, as `make` might consider that `src/propcc.ml` needs to be regenerated from the obsolete `src/propcc.ml4`. This in turn leads later to a compilation error:

```
ocamlc.opt   -w s-3+52 -warn-error A-52 -c  gObj.ml
File "gObj.ml", line 224, characters 29-41:
Error: Unbound value Signals.draw
```

**Comment by vprevosto** [comment]
@sacerdot Am I right in thinking that the following tiny addition is all that is needed in `src/propcc.ml4`?

```
diff --git a/src/propcc.ml4 b/src/propcc.ml4
index cfdfc9ea..fa26670b 100644
--- a/src/propcc.ml4
+++ b/src/propcc.ml4
@@ -87,7 +87,7 @@ let enums = [
 
 (* These types must be registered with g_boxed_register! *)
 let boxeds = [
-  "Gdk", ["Color"; "Font"; "RGBA"];
+  "Gdk", ["Color"; "Font"; "RGBA"; "Cairo" ];
   "Pango", ["FontDescription";];
   "Gtk", ["IconSet";"SelectionData";"TextIter";"TreePath"; "TreeIter";];
 ]
```

**Comment by correnson** [comment]
Yes indeed, this fixes the issue, at least on my fork.

**Comment by garrigue** [comment]
Thanks, this is now committed to `lablgtk3`
