### ISSUE TITLE
GTK3 branches cleanup

### ISSUE THREAD

**Issue by XVilka** [garrigue/lablgtk#37]
As it was indicated in the bug https://github.com/garrigue/lablgtk/issues/34 it is not clear which one is "real" GTK 3 branch, so it makes sense to remove or rename irrelevant branches, something like "legacy_blabla" or "old_blabla".

**Comment by garrigue** [comment]
Well, actually the problem in bug #34 was more or less the opposite.
I think it is clear to all the persons concerned that the active development branch is lablgtk3.
However, more advanced introspection is available in the gtk3 branch.
Moreover, renaming a branch creates complications for people who have cloned it.
(I did that for Benjamin Monate's lablgtk3 branch, now lablgtk3_monate, as I wanted to use the name for the main development branch. Fortunately, nobody seemed to be using it at that point.)

**Comment by ejgallego** [comment]
Something you may want to do @garrigue is to set the default dev branch in github to `lablgtk3`

**Comment by garrigue** [comment]
Done
