### ISSUE TITLE
gBuilder.cm* no longer distributed in beta4

### ISSUE THREAD

**Issue by sacerdot** [garrigue/lablgtk#53]
Hi,

gBuilder.ml* is no longer compiled in beta4. Therefore the code generated by lablgladecc does not
work either.

Sorry for not having check before, I was on mission and I am just back.

**Comment by ejgallego** [comment]
I'll fix that right now, thanks !

**Comment by ejgallego** [comment]
@sacerdot see #54, I hope that fixes the issues!

**Comment by sacerdot** [comment]
@ejgallego 

The .o library for ml_gtkbuilder.c is missing.

/usr/bin/ld: /home/claudio/.opam/4.07.1/lib/lablgtk3/lablgtk3.a(gtkBuilderProps.o): in function `camlGtkBuilderProps__entry':
/home/claudio/.opam/4.07.1/.opam-switch/build/lablgtk3.3.0.beta4/_build/default/src/gtkBuilderProps.ml:5: undefined reference to `ml_gtkbuilder_init'
/usr/bin/ld: /home/claudio/.opam/4.07.1/lib/lablgtk3/lablgtk3.a(gtkBuilderProps.o): in function `camlGtkBuilderProps__6':
:(.data+0x100): undefined reference to `ml_gtk_builder_get_object'
/usr/bin/ld: :(.data+0x108): undefined reference to `ml_gtk_builder_add_objects_from_string'
/usr/bin/ld: :(.data+0x110): undefined reference to `ml_gtk_builder_add_objects_from_file'

**Comment by ejgallego** [comment]
Umm, how come it did compile in my system and on CI? Maybe we should add an example to the repos?

Updating, sorry for the problem.

**Comment by ejgallego** [comment]
The fix is pretty minimal, please try to see it works, so I can update the PR otherwise.

It'd be good indeed if you could submit a test case.

**Comment by sacerdot** [comment]
I have just tested the  fix and it works. The examples/glade directory contains tests that use lablgladecc. The README is updated.

Thanks a lot for the patch. After the PR is accepted it is probably a good idea to release beta5.

**Comment by ejgallego** [comment]
I've added the examples to #54, thanks @sacerdot , as we did the dune port for the 2nd version somehow I hadn't noticed these files.

Indeed it would be a good opportunity to release beta5, and to test the new release workflow that hopefully should now work out of the box.

**Comment by ejgallego** [comment]
Closed by #55
