### ISSUE TITLE
3.0.beta6: compilation fails in invocation of ocamlmktop

### ISSUE THREAD

**Issue by treinen** [garrigue/lablgtk#65]
Hello,

my attempts to compile version 3.0.beta6 fail when building the toplevel:

````
ocamlfind ocamlmktop -package cairo2 cairo.cma  -thread  -o lablgtktop unix.cma threads.cma  \
   -I . lablgtk.cma lablgtkspell.cma lablgtksourceview3.cma gtkThread.cmo
File "_none_", line 1:
Error: Error on dynamically loaded library: /usr/lib/ocaml/stublibs/dllcairo_stubs.so: /usr/lib/ocaml/stublibs/dllcairo_stubs.so: undefined symbol: caml_ba_alloc
````

Configuration options: --with-gtkspell --with-gtksourceview3
Ocaml: 4.05
Findlib: 1.7.3
Dune: 1.6.2

-Ralf.

**Comment by ejgallego** [comment]
Hi @treinen can you provide more details? What are the exact commands you are using?

It seems to me that you are using the make-based system, AFAICK it is not supported anymore [ indeed @garrigue we should maybe merge #40 ? the windows build is working fine for Coq]

**Comment by treinen** [comment]
Hello,

yes I am using the Makefile:

````
./configure
make
````

since there is a Makefile provided.  So I guess I should instead just do a "dune build", right?

The issue itself is probably due to https://caml.inria.fr/pub/docs/manual-ocaml/libbigarray.html, but if dune is taking care of that even better. 

If the old  Makefile rules are no longer supported then maybe you should rewrite the Makefile to do the right call to dune.

-Ralf,

**Comment by ejgallego** [comment]
> If the old Makefile rules are no longer supported then maybe you should rewrite the Makefile to do the right call to dune.

Yup, that's #40 . The PR was pending on setting the Windows CI, which I failed to do so far :S

> I guess I should instead just do a "dune build", right?

Yup, be sure you are in a clean tree.

**Comment by treinen** [comment]
excellent!

is it still useful to run "./configure" before calling "dune build", then ?

**Comment by ejgallego** [comment]
@treinen in the dune build `configure` is a no-op [and removed in #40] indeed, dune does its own configuration automatically using `Configurator` [basically a wrapper around `pkg-config`]
