### ISSUE TITLE
GTK3: status_icon#set_tooltip_text is missing

### ISSUE THREAD

**Issue by talex5** [garrigue/lablgtk#69]
GTK replaced `gtk_status_icon_set_tooltip` with `gtk_status_icon_set_tooltip_{text,markup}`:

https://gitlab.gnome.org/GNOME/gtk/commit/d06e67023cf779f7af3e508de64ac1316ec08508

However, it appears that lablgtk simply deleted the method (in dc9aaadf50f3570d8912d9b09a21891522855c08).

**Comment by garrigue** [comment]
Thank you for the report.
Pull-request is welcome (if this is just a change in the props file).
