### ISSUE TITLE
GLib list

### ISSUE THREAD

**Issue by cedlemo** [garrigue/lablgtk#7]
Some examples depend on GList that you removed in the *lablgtk2on3* branch. I started to reimport from the *master* branch but it seems that in Gtk2 `GList` are used with `GtkList`. I don't know how worked `Gtk2` and `GtkList`, I just know that `Gtk3` uses `GList` like this: 

```
GList *
gtk_container_get_children (GtkContainer *container);
```

Have you got any advices on this ?

**Comment by garrigue** [comment]
This GList is unrelated. It is just an internal structure of glib. It is supported in ml_glib.h.

**Comment by XVilka** [comment]
So I think this can be closed now?
