### ISSUE TITLE
findlib lablgtk3-sourceview3 vs lablgtk3.sourceview

### ISSUE THREAD

**Issue by madroach** [garrigue/lablgtk#70]
I'm on lablgtk3-beta6
When installing ``lablgtk3-sourceview3`` via dune it is found by ``ocamlfind`` as ``lablgtk3-sourceview``.
But when installing / building via the ``Makefile`` it will show up as ``lablgtk3.sourceview``.
I suspect only the former can be sustained, so probably the Makefile based build should be either removed or adapted to install in the same way as dune does.

**Comment by garrigue** [comment]
Indeed, the Makefile is deprecated for lablgtk3

**Comment by ejgallego** [comment]
Closed by #40
