### ISSUE TITLE
cannot build the lablgtk3 pango example

### ISSUE THREAD

**Issue by martindemello** [garrigue/lablgtk#71]
I tried installing both via the released version on opam, and from github using `opam pin .`. Copying the pango1.ml example into a new project and trying to build it gives

````
$ dune build pango.exe
File "pango.ml", line 1:
Error: The files /home/mdemello/.opam/4.07.1/lib/lablgtk3/gPango.cmi
       and /home/mdemello/.opam/4.07.1/lib/lablgtk3/cairo_pango.cmi
       make inconsistent assumptions over interface Pango
````

**Comment by ejgallego** [comment]
That seems like a problem with your opam switch; can you try wiping it out ?

**Comment by martindemello** [comment]
trying from a clean switch i get

````
$ dune build pango.exe
File "pango.ml", line 32, characters 34-59:
Error: Unbound module Cairo_pango
````

the only relevant package i can see on opam is `cairo2-pango` which depends on lablgtk2. installing and depending on it anyway raises an `unbound class GPango.layout` error. Same thing happens if I opam pin the lablgtk3 branch from git.

**Comment by ejgallego** [comment]
Oh indeed, #33 was merged but #38 didn't add support for it due to the PR being submitted for a pre- #33 master. 

See #72 which should fix the problem.

**Comment by martindemello** [comment]
it does, thanks! the examples also need to be updated to call `GMain.init ()` but after that everything works fine.

**Comment by ejgallego** [comment]
Examples updated, thanks!
