### ISSUE TITLE
opam does not install a lablgtk3 executable

### ISSUE THREAD

**Issue by martindemello** [garrigue/lablgtk#74]
The docs refer to a `lablgtk3` executable, but installing via opam does not create one. If I do `./configure; make` I do get `src/lablgtk3`

**Comment by ejgallego** [comment]
Yup, I was aware of this, thanks for reporting. IMHO this script is not needed anymore as `dune utop` does provide similar functionality, but I dunno what others think.

**Comment by ejgallego** [comment]
Closed by #40
