### ISSUE TITLE
Towards an official release of lablgtk3 ?

### ISSUE THREAD

**Issue by garrigue** [garrigue/lablgtk#90]
(I'm not sure an issue is the right communication tool, but since GitHub provides no mailing lists...)

I have just released lablgtk3-3.0.beta7, which switches to a dune only build system, includes a variety of fixes, and uses a new layout for the source files.
If there is no major problem I suppose this could be a good timing to finally release an official 3.0.x.

Please report any new issue.

**Comment by ejgallego** [comment]
There have been some recent reports for CoqIDE users that could deserve more investigation; for example the  windows build seems to have some issues w.r.t. gtk2.

So you may want to wait a bit to see if we can triage these reports and some fixes would be needed.

**Comment by XVilka** [comment]
Seems these two still should be fixed before: https://github.com/garrigue/lablgtk/issues/68 and https://github.com/garrigue/lablgtk/issues/69

**Comment by garrigue** [comment]
I have now fixed (?) #68, #69, and #73 .
Is there anything stopping us from making an official release ?
It could be 3.18.0 since it require gtk+-3.18.

**Comment by XVilka** [comment]
From my experience no complains, maybe @ejgallego knows more about these CoqIDE issues, if they are still relevant.

**Comment by ejgallego** [comment]
I will ask about the status of the GTK3 port in the Coq Call tomorrow.

**Comment by ejgallego** [comment]
So indeed we discussed a bit today on how the GTK3 port of CoqIDE is working, and while there are some annoyances indeed the feeling about the API is positive so from our part a first "rc" release could happen. See the issues above linked gently by @XVilka 

Maybe the only showstopper point is about gtksourceview3 being already deprecated upstream [in favor of gtksourceview4], so indeed we would like CoqIDE to use the version 4, but this new binding could be added after the release I think.

**Comment by ejgallego** [comment]
Also @MSoegtropIMC may want to comment on how the Windows port is working.

**Comment by MSoegtropIMC** [comment]
I use CoqIDE with GTK3 on Windows and OSX almost daily and it is stable except for a few bugs which have nothing to do with GTK (e.g. that it crashes when loading files with a hyphen in the name). I also hear no negative feedback and Coq for Windows with CoqIDE has about 3000 downloads per minor release. So I would conclude that it is absolutely usable and if there are issues they are minor.

**Comment by garrigue** [comment]
I will delay a bit (at least until next week) for ocaml 4.10.beta2 to be released, as it seems that the way to access `caml_young_start/end` will change again (see https://github.com/ocaml/ocaml/issues/9205).

If `gtksourceview4` is stable enough by then, I'm happy to include it.

Btw, I'm still seeing CI errors on each of my commits on lablgtk3. This looks like noise, but I'm not sure I understand what is happening.

**Comment by ejgallego** [comment]
> Btw, I'm still seeing CI errors on each of my commits on lablgtk3. This looks like noise, but I'm not sure I understand what is happening.

Two jobs are failing for real, the 4.10+trunk fails because it tries to install campl5 [a bug in our CI], the other one is the osx job which is failing in `brew` due to some strange error I don't understand.

I can fix at least (1), for the OSX I dunno, I really don't know anything about that platform or brew other than it has been the most unstable stuff we've had in our CIs ever.

**Comment by ejgallego** [comment]
We can close this IMO.

**Comment by XVilka** [comment]
Yes, can be closed.
